version: '1.0'
services:
  web:
    image: python:3.11-slim
    container_name: django_web
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
