# Generated by Django 5.1 on 2024-08-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='link',
            name='tipo',
            field=models.CharField(choices=[('Samplicious', 'Samplicious'), ('Spectrum', 'Spectrum'), ('Cint', 'Cint'), ('Progede', 'Progede'), ('Sample-cube', 'Sample-cube'), ('Invite', 'Invite'), ('Internos', 'Internos')], default='Samplicious', max_length=50),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_de_comentario', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='links.link')),
            ],
        ),
    ]
