# Generated by Django 5.1 on 2024-08-15 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_link_likes_alter_link_tipo_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
