# Generated by Django 5.1 on 2024-08-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_remove_link_likes_delete_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
