# Generated by Django 5.1 on 2024-08-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_link_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
