# Generated by Django 5.1 on 2024-08-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_link_dislikes_link_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='link',
            name='likes',
        ),
    ]
