# Generated by Django 5.1 on 2024-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_remove_link_dislikes_remove_link_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
