# Generated by Django 5.1 on 2024-08-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_link_dislikes_link_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='dislikes',
            new_name='colocaciones',
        ),
        migrations.RemoveField(
            model_name='link',
            name='likes',
        ),
        migrations.DeleteModel(
            name='UserReaction',
        ),
    ]
