# Generated by Django 5.1 on 2024-08-15 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0013_rename_dislikes_link_colocaciones_remove_link_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='colocaciones',
            new_name='dislikes',
        ),
        migrations.AddField(
            model_name='link',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'link')},
            },
        ),
    ]
