# Generated by Django 5.1 on 2024-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0015_rename_dislikes_link_colocaciones_remove_link_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='colocaciones',
            field=models.IntegerField(default=1),
        ),
    ]
