# Generated by Django 5.1 on 2024-08-21 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0019_userconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconnection',
            name='block_time',
        ),
        migrations.RemoveField(
            model_name='userconnection',
            name='is_blocked',
        ),
    ]
