# Generated by Django 5.1 on 2024-08-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0023_loginattempt_delete_userconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginattempt',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
