# Generated by Django 5.1 on 2024-08-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0025_alter_link_nombre_alter_link_tipo_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='link',
            name='tipo',
            field=models.CharField(choices=[('Samplicious', 'Samplicious'), ('Spectrum', 'Spectrum'), ('Cint', 'Cint'), ('Progede', 'Progede'), ('Sample-cube', 'Sample-cube'), ('Invite', 'Invite'), ('Internos', 'Internos')], default='Samplicious', max_length=50),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
