# Generated by Django 5.1 on 2024-08-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0027_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
